"""remove admin column

Revision ID: 67e333fd249c
Revises: bb5689288168
Create Date: 2022-10-25 11:01:30.049833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e333fd249c'
down_revision = 'bb5689288168'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
