"""initial

Revision ID: 6820e896a76c
Revises: 
Create Date: 2022-10-25 11:07:19.439245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6820e896a76c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
