"""second

Revision ID: a72a3ae594d9
Revises: 8da460331ca1
Create Date: 2022-10-25 11:25:28.771092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a72a3ae594d9"
down_revision = "8da460331ca1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###
