"""remove is_admin column

Revision ID: bb5689288168
Revises: 002891f1b1c6
Create Date: 2022-10-24 18:41:18.098576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bb5689288168"
down_revision = "002891f1b1c6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("is_admin", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
